# -*- coding: utf-8 -*-
"""ict220.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1OFW4Nz_58wlMEBgzLUA7ijfwze2W5o
"""

import time
import random
import sys

def splash_screen():
    print("--------------------------------------------------")
    print("\033[94mHOTEL RESERVATION SYSTEM\033[0m")
    print("--------------------------------------------------")
    print("Loading", end="")
    for _ in range(6):
        time.sleep(0.5)
        print(".", end="", flush=True)
    print("\n")

def start_or_quit():
    while True:

        print("Options:")
        print("1. Start")
        print("2. Quit")
        choice = input("Select an option (1/2): ")
        if choice == '1':
            return True
        elif choice == '2':
            sys.exit("\nYou have exited the system. Thank you for visiting.")
        else:
            print("Invalid option. Please select again.")

class Reservation:
    def __init__(self, reservation_id, name, email, phone, address, check_in, check_out, room, nights, room_type, facilities):
        """
        Initializes the reservation object with user inputs.
        """
        self.reservation_id = reservation_id
        self.name = name
        self.email = email
        self.phone = phone
        self.address = address
        self.check_in = check_in
        self.check_out = check_out
        self.room = room
        self.nights = nights
        self.room_type = room_type
        self.facilities = facilities
        self.room_cost = self.calculate_room_cost()
        self.facilities_cost = self.calculate_facilities_cost()
        self.total_cost = (self.room_cost + self.facilities_cost) * self.nights
        self.tax = self.total_cost * 0.16  # 16% tax
        self.final_total = self.total_cost + self.tax
        self.trip_number = random.randint(1000000000000000, 9999999999999999)
        self.confirmation_number = random.randint(1000000, 9999999)

    def calculate_room_cost(self):
        """
        Calculates the cost based on the room type.
        """
        if self.room_type == "1 Bed":
            return 50
        elif self.room_type == "2 Queen Beds":
            return 80
        elif self.room_type == "3 Beds":
            return 100
        else:
            return 0

    def calculate_facilities_cost(self):
        """
        Calculates the additional cost for selected facilities.
        """
        total = 0
        for facility in self.facilities:
            if facility == "No Smoking":
                total += 5
            elif facility == "Desk":
                total += 3
            elif facility == "Safe":
                total += 3
            elif facility == "Coffee Maker":
                total += 2
            elif facility == "Hair Dryer":
                total += 4
        return total

    def display_reservation(self):
        """
        Displays the reservation details as per the formatted layout.
        """
        print("\033[94mYour Reservation Is Confirmed\033[0m")
        print("Thank you for your reservation. Please print your hotel receipt and show it at check-in.\n")
        print(f"Your Name: {self.name}")
        print(f"Your Email: {self.email}")
        print(f"Priceline Trip Number: {self.trip_number}")
        print(f"Hotel Confirmation Number: {self.confirmation_number}\n")

        print("---------------------------------------------------------------")
        print(f"Comfort Inn & Suites Los Alamos")
        print(f"Address: {self.address}")
        print(f"Check-In: {self.check_in} - 03:00 PM")
        print(f"Check-Out: {self.check_out} - 12:00 PM")
        print(f"Number of Nights: {self.nights}")
        print(f"Number of Rooms: 1")
        print(f"Room: {self.room} - {self.room_type}")
        print(f"Facilities: {', '.join(self.facilities)}\n")

        print("---------------------------------------------------------------")
        print("Summary of Charges")
        print(f"Billing Name: {self.name}")
        print(f"Credit Card: Mastercard (ending in 9904)")
        print(f"Room Cost: ${self.room_cost:.2f} avg. per room, per night")
        print(f"Rooms: 1")
        print(f"Nights: {self.nights}")
        print(f"Room Subtotal: ${self.total_cost:.2f}")
        print(f"Taxes & Fees: ${self.tax:.2f}")
        print(f"Total Charges: ${self.final_total:.2f} (prices are in US dollars)\n")

class Hotel:
    def __init__(self):
        """
        Initializes the hotel with a set of rooms and their availability.
        """
        self.rooms = {1: "Available", 2: "Available", 3: "Available"}

    def check_room_availability(self, room_number):
        """
        Checks if a room is available.
        """
        return self.rooms[room_number] == "Available"

    def book_room(self, room_number):
        """
        Books the room by setting it to 'Booked'.
        """
        self.rooms[room_number] = "Booked"

    def display_available_rooms(self):
        """
        Displays the available rooms.
        """
        print("Available Rooms:")
        for room, status in self.rooms.items():
            if status == "Available":
                print(f"Room {room} - Available")


def reservation_flow():
    hotel = Hotel()

    # User information taking
    name = input("Enter your name: ")
    email = input("Enter your email: ")
    phone = input("Enter your phone number: ")
    address = input("Enter your address: ")

    check_in = input("Enter check-in date (e.g., Aug 22, 2010): ")
    check_out = input("Enter check-out date (e.g., Aug 24, 2010): ")
    nights = int(input("Enter the number of nights: "))

    # Selecting Room
    while True:
        hotel.display_available_rooms()
        room_number = int(input("Select a room number: "))
        if hotel.check_room_availability(room_number):
            hotel.book_room(room_number)
            break
        else:
            print(f"Room {room_number} is already booked. Please select a different room.")

    print("Room Types:")
    print("1. 1 Bed ($50 per night)")
    print("2. 2 Queen Beds ($80 per night)")
    print("3. 3 Beds ($100 per night)")
    room_type_choice = input("Select room type (1/2/3): ")
    if room_type_choice == "1":
        room_type = "1 Bed"
    elif room_type_choice == "2":
        room_type = "2 Queen Beds"
    elif room_type_choice == "3":
        room_type = "3 Beds"
    else:
        room_type = "1 Bed"

    facilities = []
    print("Available Facilities (each with additional cost):")
    print("1. No Smoking ($5)")
    print("2. Desk ($3)")
    print("3. Safe ($3)")
    print("4. Coffee Maker ($2)")
    print("5. Hair Dryer ($4)")
    while True:
        facility_choice = input("Select a facility to add (1/2/3/4/5) or 'done' when finished: ")
        if facility_choice == "1":
            facilities.append("No Smoking")
        elif facility_choice == "2":
            facilities.append("Desk")
        elif facility_choice == "3":
            facilities.append("Safe")
        elif facility_choice == "4":
            facilities.append("Coffee Maker")
        elif facility_choice == "5":
            facilities.append("Hair Dryer")
        elif facility_choice.lower() == "done":
            break
        else:
            print("Invalid choice, please select again.")

    # Creating Reservation
    reservation_id = "R123456"
    reservation = Reservation(reservation_id, name, email, phone, address, check_in, check_out, room_number, nights, room_type, facilities)

    reservation.display_reservation()

def main():
    splash_screen()
    while True:
        if start_or_quit():
            reservation_flow()

            while True:
                proceed = input("Do you want to make another reservation? (yes/no): ").lower()
                if proceed == 'yes':
                    break
                elif proceed == 'no':
                    print("\nThank you for using the Hotel Reservation System. Goodbye!")
                    sys.exit()
                else:
                    print("Invalid choice, please enter 'yes' or 'no'.")

if __name__ == "__main__":
    main()